### ISSUE TITLE
icon size and background

### ISSUE THREAD

**Issue by guanmingwu** [reactome-idg/idg-diagram#2]
Make sure the image icon used for the view toggle button is small enough and its background is refreshed. Here it is the current view:
<img width="181" alt="Screen Shot 2019-09-19 at 4 52 26 PM" src="https://user-images.githubusercontent.com/5016634/65289091-2cd1b500-dafe-11e9-864e-e17bb0871dc1.png">

**Comment by TJBrunson** [comment]
This is just a placeholder for now. I was going to shrink it and make it white like the other icons.

**Comment by TJBrunson** [comment]
This is now fixed.
